/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.partner.info.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Partner service. Represents a row in the &quot;Partner_Partner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.partner.info.model.impl.PartnerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.partner.info.model.impl.PartnerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Partner
 * @generated
 */
@ProviderType
public interface PartnerModel
	extends BaseModel<Partner>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a partner model instance should use the {@link Partner} interface instead.
	 */

	/**
	 * Returns the primary key of this partner.
	 *
	 * @return the primary key of this partner
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this partner.
	 *
	 * @param primaryKey the primary key of this partner
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this partner.
	 *
	 * @return the uuid of this partner
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this partner.
	 *
	 * @param uuid the uuid of this partner
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the partnet ID of this partner.
	 *
	 * @return the partnet ID of this partner
	 */
	public long getPartnetId();

	/**
	 * Sets the partnet ID of this partner.
	 *
	 * @param partnetId the partnet ID of this partner
	 */
	public void setPartnetId(long partnetId);

	/**
	 * Returns the group ID of this partner.
	 *
	 * @return the group ID of this partner
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this partner.
	 *
	 * @param groupId the group ID of this partner
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this partner.
	 *
	 * @return the company ID of this partner
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this partner.
	 *
	 * @param companyId the company ID of this partner
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this partner.
	 *
	 * @return the user ID of this partner
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this partner.
	 *
	 * @param userId the user ID of this partner
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this partner.
	 *
	 * @return the user uuid of this partner
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this partner.
	 *
	 * @param userUuid the user uuid of this partner
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this partner.
	 *
	 * @return the user name of this partner
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this partner.
	 *
	 * @param userName the user name of this partner
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this partner.
	 *
	 * @return the create date of this partner
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this partner.
	 *
	 * @param createDate the create date of this partner
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this partner.
	 *
	 * @return the modified date of this partner
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this partner.
	 *
	 * @param modifiedDate the modified date of this partner
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the partnername of this partner.
	 *
	 * @return the partnername of this partner
	 */
	@AutoEscape
	public String getPartnername();

	/**
	 * Sets the partnername of this partner.
	 *
	 * @param partnername the partnername of this partner
	 */
	public void setPartnername(String partnername);

	/**
	 * Returns the licensename of this partner.
	 *
	 * @return the licensename of this partner
	 */
	@AutoEscape
	public String getLicensename();

	/**
	 * Sets the licensename of this partner.
	 *
	 * @param licensename the licensename of this partner
	 */
	public void setLicensename(String licensename);

	/**
	 * Returns the country ID of this partner.
	 *
	 * @return the country ID of this partner
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this partner.
	 *
	 * @param countryId the country ID of this partner
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the companyemail of this partner.
	 *
	 * @return the companyemail of this partner
	 */
	@AutoEscape
	public String getCompanyemail();

	/**
	 * Sets the companyemail of this partner.
	 *
	 * @param companyemail the companyemail of this partner
	 */
	public void setCompanyemail(String companyemail);

	/**
	 * Returns the companyphone of this partner.
	 *
	 * @return the companyphone of this partner
	 */
	@AutoEscape
	public String getCompanyphone();

	/**
	 * Sets the companyphone of this partner.
	 *
	 * @param companyphone the companyphone of this partner
	 */
	public void setCompanyphone(String companyphone);

	/**
	 * Returns the company po of this partner.
	 *
	 * @return the company po of this partner
	 */
	@AutoEscape
	public String getCompanyPO();

	/**
	 * Sets the company po of this partner.
	 *
	 * @param companyPO the company po of this partner
	 */
	public void setCompanyPO(String companyPO);

	/**
	 * Returns the businesscategories of this partner.
	 *
	 * @return the businesscategories of this partner
	 */
	@AutoEscape
	public String getBusinesscategories();

	/**
	 * Sets the businesscategories of this partner.
	 *
	 * @param businesscategories the businesscategories of this partner
	 */
	public void setBusinesscategories(String businesscategories);

	/**
	 * Returns the address of this partner.
	 *
	 * @return the address of this partner
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this partner.
	 *
	 * @param address the address of this partner
	 */
	public void setAddress(String address);

	/**
	 * Returns the signatory of this partner.
	 *
	 * @return the signatory of this partner
	 */
	@AutoEscape
	public String getSignatory();

	/**
	 * Sets the signatory of this partner.
	 *
	 * @param signatory the signatory of this partner
	 */
	public void setSignatory(String signatory);

	/**
	 * Returns the signatoryphone of this partner.
	 *
	 * @return the signatoryphone of this partner
	 */
	@AutoEscape
	public String getSignatoryphone();

	/**
	 * Sets the signatoryphone of this partner.
	 *
	 * @param signatoryphone the signatoryphone of this partner
	 */
	public void setSignatoryphone(String signatoryphone);

	/**
	 * Returns the signatoryemail of this partner.
	 *
	 * @return the signatoryemail of this partner
	 */
	@AutoEscape
	public String getSignatoryemail();

	/**
	 * Sets the signatoryemail of this partner.
	 *
	 * @param signatoryemail the signatoryemail of this partner
	 */
	public void setSignatoryemail(String signatoryemail);

	/**
	 * Returns the partner status of this partner.
	 *
	 * @return the partner status of this partner
	 */
	@AutoEscape
	public String getPartnerStatus();

	/**
	 * Sets the partner status of this partner.
	 *
	 * @param partnerStatus the partner status of this partner
	 */
	public void setPartnerStatus(String partnerStatus);

	/**
	 * Returns the field1 of this partner.
	 *
	 * @return the field1 of this partner
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this partner.
	 *
	 * @param field1 the field1 of this partner
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this partner.
	 *
	 * @return the field2 of this partner
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this partner is field2.
	 *
	 * @return <code>true</code> if this partner is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this partner is field2.
	 *
	 * @param field2 the field2 of this partner
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this partner.
	 *
	 * @return the field3 of this partner
	 */
	public int getField3();

	/**
	 * Sets the field3 of this partner.
	 *
	 * @param field3 the field3 of this partner
	 */
	public void setField3(int field3);

	/**
	 * Returns the folder ID of this partner.
	 *
	 * @return the folder ID of this partner
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this partner.
	 *
	 * @param folderId the folder ID of this partner
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the field5 of this partner.
	 *
	 * @return the field5 of this partner
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this partner.
	 *
	 * @param field5 the field5 of this partner
	 */
	public void setField5(String field5);

	/**
	 * Returns the region ID of this partner.
	 *
	 * @return the region ID of this partner
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this partner.
	 *
	 * @param regionId the region ID of this partner
	 */
	public void setRegionId(long regionId);

}