/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.partner.info.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Region service. Represents a row in the &quot;Partner_Region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.partner.info.model.impl.RegionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.partner.info.model.impl.RegionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Region
 * @generated
 */
@ProviderType
public interface RegionModel extends BaseModel<Region> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a region model instance should use the {@link Region} interface instead.
	 */

	/**
	 * Returns the primary key of this region.
	 *
	 * @return the primary key of this region
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this region.
	 *
	 * @param primaryKey the primary key of this region
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this region.
	 *
	 * @return the uuid of this region
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this region.
	 *
	 * @param uuid the uuid of this region
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the region ID of this region.
	 *
	 * @return the region ID of this region
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this region.
	 *
	 * @param regionId the region ID of this region
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the region of this region.
	 *
	 * @return the region of this region
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this region.
	 *
	 * @param region the region of this region
	 */
	public void setRegion(String region);

	/**
	 * Returns the partnet ID of this region.
	 *
	 * @return the partnet ID of this region
	 */
	public long getPartnetId();

	/**
	 * Sets the partnet ID of this region.
	 *
	 * @param partnetId the partnet ID of this region
	 */
	public void setPartnetId(long partnetId);

}